// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUNXZmkskCz4R3ftVd2Neh4Ngmb_EhDyQ',
    appId: '1:293421021076:web:05188c9d726ee773bc8181',
    messagingSenderId: '293421021076',
    projectId: 'monitor-bmsce',
    authDomain: 'monitor-bmsce.firebaseapp.com',
    databaseURL: 'https://monitor-bmsce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitor-bmsce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmTN-kKf8o2MHmoGmb5xk3m21YcLQsg28',
    appId: '1:293421021076:android:645cbeb2da9335d6bc8181',
    messagingSenderId: '293421021076',
    projectId: 'monitor-bmsce',
    databaseURL: 'https://monitor-bmsce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitor-bmsce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8b6A1cKNLVWxJIO729H2fsiYZlR7ix4',
    appId: '1:293421021076:ios:51870b3252268670bc8181',
    messagingSenderId: '293421021076',
    projectId: 'monitor-bmsce',
    databaseURL: 'https://monitor-bmsce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitor-bmsce.appspot.com',
    iosBundleId: 'com.example.fitbitTheme',
  );
}
